#ifndef CDHANDLER
#define CDHANDLER

class CDHandler{
	public:
		enum{
			CD_APPLICATION=1,
			CD_START_FROM,
			CD_START_TIME,
			CD_STOP_AT,
			CD_END_TIME,
			CD_DELTA_T,
			CD_WRITE_CONTROL,
			CD_WRITE_INTERVAL,
			CD_PURGE_WRITE,
			CD_WRITE_FORMAT,
			CD_WRITE_PRECISION,
			CD_WRITE_COMPRESSION,
			CD_TIME_FORMAT,
			CD_TIME_PRECISION,
			CD_RUNTIME_MODIFIABLE,
			CD_ADJUST_TIMESTEP,
			CD_MAX_CO,
			CD_MAX_ALPHA_CO,
			CD_MAX_DELTA_T,
			CD_FUNCTION
		};


};

#endif
